### ISSUE TITLE
Can't submit a prompt

### ISSUE THREAD

**Issue by JuleKnowHow** [stuartridout/promptbuddy#10]
Unfortunately, I cannot submit new Prompts as of right now. 
When I open a Category, e.g. Copilot (M365), and put in my Title and Description, there still is a red text that tells me "You must add at least one app tag" - but Copilot (M365) is already put in. I cannot submit the prompt, because the button is deactivated. 
It does not help to remove and set the tag or to set other tags. The red text remains and I can't submit the prompt.
![image](https://github.com/stuartridout/promptbuddy/assets/164504962/e53ed6b4-7c3d-4421-aa40-dcaac956a98c)

**Comment by Erithano** [comment]
@JuleKnowHow  - Thanks for submitting. You're missing the Prompt input field. That's what's causing the issue.
Please reinstall the latest version and follow the video instructions closely. Do not Play the app in Power Apps first time. 

Should look like this:
![image](https://github.com/stuartridout/promptbuddy/assets/65014935/758d7be7-6c86-4d6e-92ba-493ff49fae73)

Good luck!
