### ISSUE TITLE
How to enable it for EDU-Teams

### ISSUE THREAD

**Issue by kurtsoeser** [stuartridout/promptbuddy#11]
Hi!

I tried this fantastic solution and I wanted to install it to a Course Team /EDU Team, but I get an error 

As I really want this cool tool to wwork with my students and I am not really knowing any stuff about PowerApps, maybe some can help me?

**Comment by Erithano** [comment]
Hey @kurtsoeser - Currently we have not made any adjustments to support a "Course Team /EDU Team".
Thanks for reporting the error! This type of team has special requirements and might not be supported at this time.

Prompt Buddy can also be installed in Dataverse as a normal Power App. 
It would then require a per app or per user license to use it. Hope that helps!

One tip is to ask our super EDU colleague Mike Tholfsen https://www.youtube.com/channel/UC2dSE9W3lGYbFi_CPmVtA-A 

We can ask him internally as well 👍

**Comment by Erithano** [comment]
Not planned as of now. Will inquire with our EDU specialists.
