### ISSUE TITLE
Translated labels for the following languages could not be imported because they have not been enabled for this organization: 1036

### ISSUE THREAD

**Issue by onlize** [stuartridout/promptbuddy#13]
Hello, I am following the steps in the video. After I imported the file, I received the following warning:

`Customizations from file "PromptBuddy_1_0_1_4.zip" imported successfully with warnings: Translated labels for the following languages could not be imported because they have not been enabled for this organization: 1036`

What does it mean and is this a problem?

It offered me to download logs, so here is the log that I downloaded.
[PromptBuddy_1_0_1_4.zip_import.zip](https://github.com/stuartridout/promptbuddy/files/14912875/PromptBuddy_1_0_1_4.zip_import.zip)

**Comment by Erithano** [comment]
@onlize - Not a problem ✔️. 

In the future we plan to allow Prompt Buddy to automatically match the language used in Teams. It's not enabled yet.
That means you'd see the few UI elements, such as "Submit a prompt" in your language. I'm guessing you're in Germany 😉.
1036 is a language code for German (Germany) in the context of PowerApps.

The current version has English UI only.

**Comment by RolfCloud42** [comment]
1036 is French ;-) I had the same error and there are two ways to handle it. 
1. (recommended) Enable the language in the environment.
2. (Crude & rude) Edit the XML and delete the language reference at the end of the file :-)

**Comment by onlize** [comment]
@Erithano, I am in USA.

**Comment by onlize** [comment]
@RolfCloud42. It looks like everything is installed and working, I am not sure what and if I should do something.

**Comment by onlize** [comment]
Thank you!

**Comment by Erithano** [comment]
[like]  Erik Olsson reacted to your message:
________________________________
