### ISSUE TITLE
Prompt samples

### ISSUE THREAD

**Issue by knza001** [stuartridout/promptbuddy#14]
Hello ! 

How can I get the sample prompts without deploying the app please ?

**Comment by stuartridout** [comment]
Here you go

[
    {
        "Category": "Copilot (M365)",
        "Description": "This prompt looks across your emails, chat and channels to find where you've been mentioned and then gives you the top items you should do today.",
        "ID": "c5b5062c-a2bb-ee11-9078-0022481b5b6a",
        "Prompt": "Summarize where I was mentioned in email, Teams chat and channels in the last 24 hours and using that information prioritize my top 3 action items for today.",
        "Title": "Start the day right - Catch up with where you've been mentioned"
    },
        {
        "Category": "Copilot (M365)",
        "Description": "You've just got back from vacation and your Inbox is full - just give me the most important actions that are pending my return in order of priority please!\n",
        "ID": "54e0c4f7-31e6-ee11-904d-0022481b58d3",
        "Prompt": "Summarise the last 7 days into bullet points of actions where I have been mentioned. Refer to any emails, chats and meeting transcripts that I missed due to being on vacation. List the urgent actions first and who asked the question",
        "Title": "I've been away for 7 days!"
    },
    {
        "Category": "Copilot (web)",
        "Description": "Your Perfect Persona✨Impressive Output - Tiny Effort. Let's Go! 🎯 (Like and/or comment if you try it)\nThis is an advanced prompt made simple to use. Copilot crafts a perfect persona to tackle ANY problem or opportunity with several iterations. Best part? -Copilot can answer the persona's questions for you! \nYou provide nothing or what you want/know. When you're done, just ask for the solution.",
        "ID": "0896d5e3-e3e5-ee11-904d-0022481b5de7",
        "Prompt": "For a problem or opportunity, which you will ask me about and I will then provide, you will craft the perfect persona (please include relevant experience and qualifications when describing the persona) to solve the problem. Act as a mediator between me and the persona by asking me the 3 most relevant questions to assist the persona with finding the best solution.\n \nOnce you have finished your response, if I type \"answer\" then please provide answers to the 3 questions posed by the persona. Then propose a solution. You must always add 3 new questions from the persona to further iterate the solution.\n \nFor every response ensure you end by asking \"If you would like me to provide responses to the [Insert Persona Name] questions on your behalf to further the solutioning, type \"answer\". If you would like to add additional information simply type in the additional information below and [Insert Persona Name] will review with the aim to provide the best solution. If you would like to view the detailed solution, including plan and estimated costs based on responses captured, type \"solution\"\".\n \nContinue our iteration process by always adding answers to the persona's 3 most recently asked questions in your reply, if I type \"answer\". \n\nIf there are questions from the persona after a solution is presented, please offer to answer those. Then offer to update the solution's existing information if I type \"solution\".\n\nIf you can carry out this task, simply respond \"Please let me know what opportunity or problem you would like to investigate.\"",
        "Title": "Your Perfect Persona✨For ANY Problem/Opportunity"
    },
    {
        "Category": "Copilot (web)",
        "Description": "Nobody knows everything but you can leverage your expertise in one area to quickly learn similar topics.   You can keep asking questions at an advanced level, or change the prompt and expertise to suit yourself.",
        "ID": "7a21882c-c7be-ee11-9079-0022481b5de7",
        "Prompt": "Act as if you are a colleague, we both have advanced degrees in psychology, however I have not studied ADHD before, and you are explaining it to me in terms that I already understand from traditional psychology.",
        "Title": "Learn advanced topics from a peer"
    },
    {
        "Category": "Copilot (M365)",
        "Description": "Converting Time Zones accurately can be a challenge, and while we have tools that can help with scheduling, you occasionally may still find yourself with a list of people's availability that you are trying to decipher as you hunt for the best meeting time. ",
        "ID": "af580bcf-53cd-ee11-9079-0022481b5c84",
        "Prompt": "I am trying to find the best meeting time for the greatest number of participants, I understand we may not find a time that works for everyone. They are across several Time Zones. Please take the timeslots listed below of their availability and provide a list converting all times to Pacific Standard Time (PST). Then please provide the two options where the most numbers of schedules overlap:\n \nIndividual 1:\n2/22/24 8:00-9:00 PST\n2/22/24 10:30-11:30 PST\n \nIndividual 2:\n2/22/24 9:00-11:00 MST\n2/22/24 12:30-2:30 MST\n \nIndividual 3:\n2/22/24 10:00 -11:30 EST\n2/22/24 1:30-2:30 EST\n \nIndividual 4\n2/22/24 11:30 -2:00 CST\n2/22/24 8:00-9:00 CST",
        "Title": "Convert Timezones and Find Common Meeting Slot"
    },
    {
        "Category": "Designer",
        "Description": "This prompt creates thumbnails for categories in the Prompt Buddy style.",
        "ID": "c5b5062c-a2bb-ee11-9078-0022481b5b61",
        "Prompt": "Origami art representing finance as a business department, in gradient colors and dark background.",
        "Title": "Generate new category images in the Prompt Buddy style"
    }
,
    {
        "Category": "Copilot (M365)",
        "Description": "Support better meeting engagements by getting all the details in one place before the meeting takes place including previous engagement topics and what questions to ask.",
        "ID": "bcc711ed-64c6-ee11-9079-0022481b5c84",
        "Prompt": "Provide a meeting briefing from the references in readable format that includes the title of the meeting, client organisation name, client contact name, detailed background information about the organisation, reason for the meeting, objectives, list other information available about the organisation, talking points associated with the subject matter, generate a list of 5 questions that are related with the client or subject matter.\nReferences: /[email or doc references]",
        "Title": "Create a rich pre-meeting briefing document from existing emails"
    },
    {
        "Category": "Copilot (M365)",
        "Description": "After a long dont you want to wrap up your day, get a list of your tasks from your meetings and prepare for tomorrow. But wait, when do you even have time for a break? Copilot will help!",
        "ID": "b6b8bce5-fce2-ee11-904c-6045bd0b1901",
        "Prompt": "Dear Copilot, Id love your help on wrapping up my day and preparing for tomorrow.\n\nPlease name the first section: Today \nCan you please write a short paragraph of my work today and separately list tasks that came from my meetings?\nAlso highlight my important things from my email based on your analysis.\n\nIn the next section named Your Meetings Tomorrow\nThen, can you please help me with an overview of my meetings tomorrow. Create a table and list who organized the meeting and add details of the meeting. Please also show the category you would place that meeting (personal, internal, external or traveling) in and add any important things I need to know about the meeting.\nPlease show me what % of time I am spending on the different categories in a list.\n\nIn the last section named: Get prepared\nFinally, as my personal assistant, please write a small summary and brief me on all the important things I need to know to make tomorrow a productive day and please suggest when I should consider taking breaks.\n",
        "Title": "Wrap up your day and get prepared"
    },
    {
        "Category": "Copilot (web)",
        "Description": "This is a prompt I use to refine and elevate my prompts. Yeah, I know... \nRegardless of topic/action/want/outcome, this prompt will help you define your ask to Copilot. You'll be asked questions you otherwise wouldn't consider. You decide for how long. It helps you provide the level of detail you have in mind, but struggle to articulate.  Any topic, including image generation works with this prompt!",
        "ID": "cc239b19-c3be-ee11-9079-0022481b58d3",
        "Prompt": "I want you to become my Prompt engineer. Your goal is to help me craft the best possible prompt for my needs. The prompt will be used by you, copilot. \n\nYou will follow the following process:\n\n1. Your first response will be to ask me what the prompt should be about. I will provide my answer, but we will need to improve it through continual iterations by going through the next steps.\n\n2. Based on my input, you will generate 2 sections. \n\na) Revised prompt (provide your rewritten prompt. It should be clear, concise, and easily understood by you)\n\nb) Questions (ask any relevant questions pertaining to what additional information is needed from me to improve the prompt).\n\n3. We will continue this iterative process with me providing additional information to you and you updating the prompt in the Revised prompt section until I say we are done.",
        "Title": "One Prompt To Rule Them All"
    },
    {
        "Category": "Copilot (web)",
        "Description": "Is the video too long to watch?  Open Copilot in the sidecar in Edge and you can ask questions about the video.",
        "ID": "a7763e60-12c5-ee11-9079-0022481b5df7",
        "Prompt": "Summarise this video",
        "Title": "Summarise a YouTube video"
    },
    {
        "Category": "Copilot (web)",
        "Description": "Copilot for the web is extremely useful for learning about topics. But if you just ask it to explain something then the response may be no easier to understand than from a site you find from a search engine. \n\nThe benefit to using Copilot is that you can tell it to explain in a way you will find easy to understand. Without sounding patronising, the best way to do this is by asking it to explain your chosen topic to you as if you were a child. \n\nView the image. Note how the response is on a complex topic like Quantum Computing. \nWhen you ask Copilot to explain it to you as if you're six years old. It will make the text much simpler to read and understand. ",
        "ID": "4cdb5919-60bc-ee11-9078-0022481b5444",
        "Prompt": "Explain [insert topic] as if I'm six years old.",
        "Title": "Explain to me as if I'm six years old."
    },
    {
        "Category": "Designer",
        "Description": "Use Designer to create a great image that you can use as a profile pic on your socials, LinkedIn or on presentations.  This is an example but you can personalise this to make it work for you.",
        "ID": "84517995-2dbc-ee11-9078-0022481b5c84",
        "Prompt": "cartoon style man with a smile on the front, wearing a black collared shirt, brown eyes, wears black large glasses and short brown classic slick backed hair. Holding a Microsoft laptop. text 3D rendering, typography, illustration, painting, photo, poster, 3d render",
        "Title": "Create a 3d image of you"
    },
    {
        "Category": "Excel",
        "Description": "Pivot tables are tricky. Use this prompt to let copilot in Excel create one for you based on your needs.\nYou get a preview and can add to a new sheet. Check the video link for a live example.\n\nView the prompt in use here (2min video)",
        "ID": "da369df0-1fc5-ee11-9079-0022481b558d",
        "Prompt": "Create a pivot table highlighting <variable>, <variable>, and <variable>",
        "Title": " Create a Pivot table highlighting things you need"
    },
    {
        "Category": "Excel",
        "Description": "Columns with numbers? Yes. Need a new one based on existing ones? Yes.\nTry this prompt. You get the formula AND the explanation.\n\nView the prompt in use here (2min video)",
        "ID": "1c7679b5-1fc5-ee11-9079-0022481b558d",
        "Prompt": "Create a column that subtracts <column name> from <column name>",
        "Title": "Create new colums based on existing data"
    },
    {
        "Category": "Copilot (M365)",
        "Description": "This maybe obvious, but change is hard. Its good to remind customers that M365 Copilot is more than just a helper. It is a partner that empowers us to work smarter, faster, and better. By changing our workflow to include asking for advice, we can leverage the power of M365 Copilot to create more impactful results. ",
        "ID": "8b60bbe4-b8dc-ee11-904d-0022481b574a",
        "Prompt": "Example prompt:\nGiven the data set below, what is the best way to analyze for profit and engagement. Please suggest additional columns that are needed for the analysis. M365 Copilot Excel Sample Data.xlsx",
        "Title": "Ask Copilot"
    },
    {
        "Category": "Forms",
        "Description": "A way to build a large Likert-scale survey, which can be time consuming to build, to gather ratings on a series of features or other items.",
        "ID": "cc50c10d-63e0-ee11-904c-002248c7f6a1",
        "Prompt": "A survey of requirements for [solution] features. Respondents should use a series of 5 Likert questions that each contain 10 features to score based on how critical they are for the organisation. The question for all 5 items can be \"Score the following features based on their usage. The scores are: 1. Unknown, 2. Not important, 3. Nice to have, 4. Should have, and 5. Must have.\" The 5 options for the Likert scale should be, in order: \"unknown\", \"not imp\", \"nice\", \"should\", or \"must\". \n\nThe list of features is as follows. This should be split into 5 Likert questions of 10 features (rows) each:\n\nQuestion 1\nFeature\nFeature\nFeature\n\nQuestion 2\nFeature\nFeature\nFeature\n\nQuestion 3\nFeature\nFeature\nFeature\n\nQuestion 4\nFeature\nFeature\nFeature\n\nQuestion 5\nFeature\nFeature\nFeature\n",
        "Title": "Requirements Gathering"
    },
    {
        "Category": "Forms",
        "Description": "Feedback form to follow up from a sector briefing, event or webinar suitable to share with clients.",
        "ID": "7028fe65-0fc1-ee11-9079-0022481b558d",
        "Prompt": "Propose a sector briefing feedback survey to collect attendee feedback from customers on clarity of communication, relevance of topics, overall effectiveness of the event, venue and time preferences, and ask suggestions for future improvement. Include permission to contact for follow up.",
        "Title": "Sector briefing, event or webinar feedback"
    },
    {
        "Category": "Loop",
        "Description": "This prompt creates a set of questions for a guided conversation in your 1:1.  The great thing is that each time you use it the questions are slightly different so you get a different perspective each time.",
        "ID": "007ccb46-a8bb-ee11-9078-0022481b58d3",
        "Prompt": "Make an agenda with today's date /date and 3 questions as section headings: How are you doing, how can I help and other business. Put two points in each section that are sample questions, with a personal tone, this agenda is about wellbeing and personal productivity, not a project review.",
        "Title": "Create a conversation structure for 1:1 "
    },
    {
        "Category": "Loop",
        "Description": "Pasted something useful into Loop and the formatting is a bit dull?  Highlight the text and use Rewrite -- and instruct it just to improve the formatting to make it stand out without ",
        "ID": "9acf8f93-e4be-ee11-9079-0022481b558d",
        "Prompt": "Rewrite: Use formatting of text to make it more readable.",
        "Title": "Improve dull formatting inside Loop"
    },
    {
        "Category": "OneNote",
        "Description": "Keep on top of pending actions across my OneNote",
        "ID": "46cc0175-b2e2-ee11-904d-0022481b5c84",
        "Prompt": "Summarise in a table all the actions I have outstanding across my notebook",
        "Title": "Keep on top of pending actions across OneNote "
    },
    {
        "Category": "Outlook",
        "Description": "Crafting a written prompt can sometimes take a lot of time, especially if you're seeking perfection. For some email generation use cases, using dictation in Outlook means you can speak and use your natural language to instruct Copilot in Outlook.",
        "ID": "0ca694c4-39dd-ee11-904d-0022481b5df7",
        "Prompt": "* Windows Key + H to start dictation > speak your prompt!*",
        "Title": "Speed up your email prompt with dictation"
    },
    {
        "Category": "Outlook",
        "Description": "Summarize emails where I was mentioned recently",
        "ID": "3774c239-a4d0-ee11-9079-0022481b558d",
        "Prompt": "Summarize emails where I was mentioned recently. Make it detailed, highlighting the sender and categorizing by topic of the email.",
        "Title": "Catch up - summarize where I was mentioned"
    },
    {
        "Category": "PowerPoint",
        "Description": "Need an image in your slide.  Ask Copilot to find it for you.",
        "ID": "87883223-b5be-ee11-9079-0022481b5df7",
        "Prompt": "Add an image of a tree to this slide. In a field with lots of blue sky.",
        "Title": "Add an image to a slide"
    },
    {
        "Category": "PowerPoint",
        "Description": "Copilot can make sure your presentations are accessible to all",
        "ID": "a6f6a760-ede1-ee11-904d-0022481b58d3",
        "Prompt": "Suggest accessibility improvements for these slides",
        "Title": "Make your deck accessible "
    },
    {
        "Category": "Teams",
        "Description": "Have you been in one of those meetings where everyone introduces themselves and their roles?  You're frantically trying to scribble down the information!  This prompt solves that for you.",
        "ID": "81a24780-c4be-ee11-9079-0022481b5444",
        "Prompt": "List the participants in the meeting and their roles in a table format.",
        "Title": "Who are the meeting participants?"
    },
    {
        "Category": "Teams",
        "Description": "Summarize an ongoing meeting or recorded meeting with a simple prompt. \nIf you don't know what you're lookng for, simply remove the \"about\" part and just have \"Summarize what whas discussed\"\n\n",
        "ID": "843d99af-49bc-ee11-9078-0022481b58d3",
        "Prompt": "Summarize what was discussed about [choose a specific word, activity or point of interest you might have]",
        "Title": "Summarize Meetings (ongoing or recorded)"
    },
    {
        "Category": "Whiteboard",
        "Description": "a sample promt for generate suggestion on how to educate users on copilot",
        "ID": "c968fc58-a7d0-ee11-9079-0022481b5de7",
        "Prompt": "Suggest ways to educate users on Copilot in Microsoft Whiteboard",
        "Title": "Generate suggestions"
    },
    {
        "Category": "Teams",
        "Description": "Use Copilot to generate relevant questions",
        "ID": "08e77eb8-a7d0-ee11-9079-0022481b5de7",
        "Prompt": "Suggest 3 questions to ask the main speaker",
        "Title": "generate relevant questions"
    },
    {
        "Category": "Whiteboard",
        "Description": "As notes are added to the Whiteboard, it can get difficult to organize the content.  Copilot in Whiteboard can quickly organize the data into meaningful categories.",
        "ID": "35c0ae76-a7d0-ee11-9079-0022481b5444",
        "Prompt": "1.\tSelect All Sticky notes\n2.\tClick ‘Categorize’\n",
        "Title": "Organize Ideas"
    },
    {
        "Category": "Word",
        "Description": "This simple prompt helps me ensure I'm conveying the important point(s) and being consistent in my communications. ",
        "ID": "a0f380e4-5dda-ee11-904d-0022481b5de7",
        "Prompt": "What's the key message of this content?",
        "Title": "Identify key messages"
    },
    {
        "Category": "Word",
        "Description": "Will provide a summary of key bullet points from a Word Document",
        "ID": "018b6286-b7db-ee11-904d-0022481b5df7",
        "Prompt": "give me a bullet list of key points",
        "Title": "Getting Key Bullet Points"
    },
    {
        "Category": "Word",
        "Description": "This is a prompt for all those PMs out there that are responsible to building program or project plans and need to started building an estimate. ",
        "ID": "ff403b3d-bbdc-ee11-904d-0022481b5363",
        "Prompt": "I need a high level program plan estimate for a [what ever is being built]. This should be done in xx phases: phase 1 should include [enter brief description] phase 2 should include [enter brief description], phase 3 [enter brief description],  phase 4 [enter brief description] Phase 5 and 6 will be [enter brief description] We would like to start this project in [July-October of 2097] and complete phase 4 [ by September 2099.]\n\n",
        "Title": "Create High Level Project Plan Estimates"
    }
]
