### ISSUE TITLE
Turning off Notifications doesn't work

### ISSUE THREAD

**Issue by checkso** [stuartridout/promptbuddy#15]
I toggled the notifications on in the beginning, but now we are thinking we might not need it.
Disabling the notifications, doesn't work. Notifications still coming.
Is there a flow which I can disable?

**Comment by stuartridout** [comment]
OK, I can see some odd behaviour here.  Looking into it now.

**Comment by Louicha** [comment]
When the default value of the toggle "tglIdeaDetailControls_PostToTeams" in the "Campaign Detail Screen" is set to false, it seems to work.

**Comment by stuartridout** [comment]
Fix for notifications in 1.0.2.0 release
