### ISSUE TITLE
Overview shows wrong count of prompts

### ISSUE THREAD

**Issue by checkso** [stuartridout/promptbuddy#16]
After deleting a prompt the main dashboard shows all prompts (actual + deleted)

<img width="248" alt="image" src="https://github.com/stuartridout/promptbuddy/assets/11270200/8de29c7d-0670-4788-806f-75c0b25ae3b2">

expected behaviour: shows only the actual number

**Comment by stuartridout** [comment]
We've identified that there is an error when deleting a prompt.  There is a fix coming for this tomorrow 🤞

It will still require a manual fix for the prompts that have already been deleted.  This will require moving the erroneous rows from the Employee Idea Campaign Links table.  These rows are the ones with a blank 'Linked Idea' value in the table.

**Comment by stuartridout** [comment]
Fix for deleting prompts in 1.0.2.0 release
