### ISSUE TITLE
"Team owner restricted" also excludes the owners

### ISSUE THREAD

**Issue by Louicha** [stuartridout/promptbuddy#17]
If I activate the "Team owner restricted" setting, I can no longer make any changes to the campaigns, even as the owner of the associated team. The only way to reactivate it is to change the entry in the Dataverse table.

**Comment by Mariann1812** [comment]
Same here. Can't add categories neither edit. Option is greyed out.

**Comment by stuartridout** [comment]
Are you the team owner?

**Comment by Mariann1812** [comment]
Yes, I am.
I reinstalled Prompt Buddy to restore access.

Thanks!
Mariann


Mariana Ferola

E: ***@***.******@***.***>

P: 305-458-5821

[LinkedIn LinkedIn icon]<https://linkedin.com/in/marianaferola> marianaferola<https://linkedin.com/in/marianaferola>



________________________________

**Comment by Erithano** [comment]
Please update to the latest version of Prompt Buddy or reinstall as per @Mariann1812's fix 👍
