### ISSUE TITLE
Sample prompts do not import and no categories

### ISSUE THREAD

**Issue by halukpn** [stuartridout/promptbuddy#19]
After installing the app, in Manager there are no categories. Importing the sample prompts then fails.

I can manually create the categories, but something has gone wrong with the app creation as there are no categories.
![2024-04-30 09_31_10-Teams and Channels _ General _ UK Power Networks _ Hal Sclater@ukpowernetworks c](https://github.com/stuartridout/promptbuddy/assets/157490603/5348c6fd-97ad-432d-bdf5-478fe1f38688)

**Comment by halukpn** [comment]
After adding one category manually
![2024-04-30 09_42_54-Teams and Channels _ General _ UK Power Networks _ Hal Sclater@ukpowernetworks c](https://github.com/stuartridout/promptbuddy/assets/157490603/ae849f95-b8fe-422c-ac89-4baa089985ca)
, the import for that category works:

**Comment by stuartridout** [comment]
Have you run the manager app or are you doing this in the editor?  You need to run the app fully to generate the categories. 

Before you do that you'll need to clear ALL tables of any data so that it will start the import process for Categories.  Delete all rows in all tables and then run the Manager app in full mode (not in the editor).

**Comment by halukpn** [comment]
> Have you run the manager app or are you doing this in the editor? You need to run the app fully to generate the categories.
> 
> Before you do that you'll need to clear ALL tables of any data so that it will start the import process for Categories. Delete all rows in all tables and then run the Manager app in full mode (not in the editor).

This is opening the app in Teams, your video shows all the categories being created. I did not run the app in Power Apps.

**Comment by halukpn** [comment]
> Have you run the manager app or are you doing this in the editor? You need to run the app fully to generate the categories.
> 
> Before you do that you'll need to clear ALL tables of any data so that it will start the import process for Categories. Delete all rows in all tables and then run the Manager app in full mode (not in the editor).

How do I clear out all the tables please? Because a lot of things are messed up even after manually creating the categories.

**Comment by halukpn** [comment]
OK sorted this by deleting all the data in the tables as you suggested, thanks
