### ISSUE TITLE
Edit prompts and change assignements

### ISSUE THREAD

**Issue by RossParkman** [stuartridout/promptbuddy#2]
Is it possible to be able to edit a prompt once created (i can't see there is a way to do this in the app at present) and also it would be great to have a picker for each prompt to be able to add to a persona/dept/app when they exist.

Thanks!

**Comment by RolfCloud42** [comment]
HI, all worked out as described in the video. Big thanks for that. One element that I want to suggest is to have a icon at the prompt to copy the prompt to the clipboard for pasting it into the respective app.. Yes, we all know how to copy and paste but wouldn't that be so much more convenient?
I tried to add that myself in the solution but the naming and layering of the app did not make it easy to find. Any pointers would be highly appreciated.

**Comment by Erithano** [comment]
@RossParkman - Thaks for contributing! Until we catch up with our backlog, I suggest this workaround for now:
Have an admin delete the prompt you want to edit and simply re-submit it. 
(Just FYI: Also on the backlog and live in internal version - users can delete their own submitted prompts)

**Comment by RossParkman** [comment]
Thanks - out of interest i can see that Copilot Lab looks to be getting similar prompt sharing abilities - how do you see this playing out with PromptBuddy?

**Comment by Erithano** [comment]
@RossParkman  - We get this question a lot. 

Here's a **Short**, **Medium** and **Long** answer depending on how detailed you want it.

### Short answer

> No compete - They complement each other 💗


### Medium answer

> Prompt Buddy is free sample code in the form of a Power App hosted and managed exclusively by the customer (user).
> Customers (users) own it and can change/add/remove anything. It's their template as soon as it's downloaded.
> Customers (users) can add custom internal Copilots and other AI apps in their ecosystem as prompt categories.
> 
> Copilot Lab requires a copilot license and is a managed Microsoft product. Microsoft decides on features and visuals etc.
> 
> An internal prompt can be found in Prompt Buddy and easily added/saved as a bookmark in Copilot Lab.

### Long answer 
_In collaboration with Copilot for the web_

This is what we, together with Copilot for the web, have to say:

> Certainly! 
Let’s delve into the value that Prompt Buddy offers to customers, especially when compared to Microsoft Copilot Lab:
> 
> **Customization and Ownership**
> 
> _Prompt Buddy_ 
> Customers have the freedom to own, edit, and add features or visuals to Prompt Buddy. 
> This level of customization allows teams to tailor the app to their specific needs. Whether it’s adding company-specific prompts, adjusting the user interface, or incorporating branding elements, Prompt Buddy becomes a truly personalized tool.

> _Microsoft Copilot Lab_ 
> In contrast, the features and visuals of Copilot Lab are controlled by Microsoft. 
> While this ensures consistency and security, it may limit the ability to fine-tune the experience to match individual team preferences.
>  
> **Licensing Flexibility**
> 
> _Prompt Buddy_ 
> One of the standout advantages is that Prompt Buddy can be used by anyone, regardless of their licensing status. Whether you’re a licensed Copilot for Microsoft 365 user or not, you can still benefit from Prompt Buddy’s prompt-sharing capabilities within Teams.
>
> _Microsoft Copilot Lab_ 
> To access Copilot Lab, users need a Copilot license. While this aligns with enterprise licensing models, it may exclude certain team members who don’t have dedicated Copilot licenses.
>  
> **Empowering Teams and Individuals**
> 
> _Prompt Buddy_ 
> By allowing customization and unrestricted access, Prompt Buddy empowers both teams (through collaboration) and individual users (for personal productivity). It bridges the gap between collective knowledge and individual creativity.
>
> _Microsoft Copilot Lab_ 
> Primarily aimed at individual users, Copilot Lab provides a rich set of prompts for personal development. However, it doesn’t inherently foster team collaboration in the same way Prompt Buddy does.
>  
> **Holistic AI Adoption**
> 
> _Prompt Buddy + Copilot Lab_ 
> When used together, Prompt Buddy and Copilot Lab create a holistic environment for AI adoption. Teams can share insights, learn from ready-made prompts, and apply them individually. It’s a win-win scenario where customization meets curated content.
> 
> In summary, Prompt Buddy’s flexibility, ownership, and inclusivity make it an excellent companion for teams and individuals. When combined with Copilot Lab, organizations can maximize the benefits of AI-driven productivity while maintaining control over their unique requirements. 🚀✨

**Comment by stuartridout** [comment]
You can now edit prompts in the latest version.

**Comment by dlenclume** [comment]
Am I right that users will at the very least need access to Power Apps in Teams?  But what about if I wanted to add a link to Prompt Buddy in say Viva Engage.  Does that work?

**Comment by Erithano** [comment]
> Am I right that users will at the very least need access to Power Apps in Teams? But what about if I wanted to add a link to Prompt Buddy in say Viva Engage. Does that work?

@dlenclume 
Users need access to Teams and also need to be be members of the team where Prompt Buddy is installed. Users do not need paid Power Apps licenses to use Prompt Buddy within Teams.

Only the person (admin/manager/team owner) needs access to the Power Apps app in Teams to deploy Prompt Buddy (takes about 5 minutes - follow our video in the main page of this repo).


Once deployed in Teams you can easily get a direct link to Prompt Buddy. Just right click the tab where you access Prompt Buddy in your team and select copy link to tab. That URL can be pasted anywhere, including on Viva Engage, and will take users (team members in the team where Prompt Buddy is installed) directly to Prompt Buddy. 

This link is also easy to bookmark in your browser for example 👍.

_PS. This applies to using Prompt Buddy within Teams. No additional licensing required. It's also possible to use Prompt Buddy outside of Teams (such as in the browser) but that will require Power Apps per user or per app licensing_

**Comment by dlenclume** [comment]
Official

Hello

I've tried what you've suggested but it seems that the only way this will work is if you have a power apps premium licence.  I've tried copying and pasting the link in a browser or in Viva Engage but I get the following error:
[cid:b78384fd-27d4-43c6-9122-47cc4f082075]

Is as though it's looking for a Power Apps premium trial which I no longer have.

Is there something I'm doing wrong.  The link I copy from the app in Teams shows like this: https://apps.powerapps.com/play/e/0be444cf-aad9-e90f-8340-bc20a5e4b7ac/a/bbc0d678-abfb-4daf-ae6b-e4b15475cf2d?connections=premium

The fact that it has premium in the url suggests it is looking for a premium licence.

Is there anyone that can spare 5 minutes on a call?

Thanks


David L’enclume

M365 Application Specialist



Corporate IT – Workflow Team

Richmond and Wandsworth Councils

Fairfield Annexe, Fairfield Road, SW18 2PU

Tel: 020 8871 8106

Email: ***@***.******@***.***>

***@***.***?anonymous&ep=bwmEmailSignature>             Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>

________________________________

**Comment by Quickieorg** [comment]
> Official
> 
> Hello
> 
> I've tried what you've suggested but it seems that the only way this will work is if you have a power apps premium licence.  I've tried copying and pasting the link in a browser or in Viva Engage but I get the following error:
> [cid:b78384fd-27d4-43c6-9122-47cc4f082075]
> 
> Is as though it's looking for a Power Apps premium trial which I no longer have.
> 
> Is there something I'm doing wrong.  The link I copy from the app in Teams shows like this: https://apps.powerapps.com/play/e/0be444cf-aad9-e90f-8340-bc20a5e4b7ac/a/bbc0d678-abfb-4daf-ae6b-e4b15475cf2d?connections=premium
> 
> The fact that it has premium in the url suggests it is looking for a premium licence.
> 
> Is there anyone that can spare 5 minutes on a call?
> 
> Thanks
> 
> 
> David L’enclume
> 
> M365 Application Specialist
> 
> 
> 
> Corporate IT – Workflow Team
> 
> Richmond and Wandsworth Councils
> 
> Fairfield Annexe, Fairfield Road, SW18 2PU
> 
> Tel: 020 8871 8106
> 
> Email: ***@***.******@***.***>
> 
> ***@***.***?anonymous&ep=bwmEmailSignature>             Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
> […](#)

Have the same issue.
Did you resolve it?
