### ISSUE TITLE
Can't submit prompts

### ISSUE THREAD

**Issue by kayleeg00se** [stuartridout/promptbuddy#20]
Even though I'm an owner of the team, (and owner restriction setting is off), I'm not able to submit prompts. I have filled out every field on the form but the Submit prompt button is still disabled. 
![2024-05-01 11_59_29-Window](https://github.com/stuartridout/promptbuddy/assets/53491718/def72d7a-a8f5-46c8-b0cd-2c3ee7fd5cd4)

**Comment by stuartridout** [comment]
Something has gone wrong with the category set up.  There should be a prompt field but that's not showing.  That's what's stopping you submitting.  

Is it a new install?

I assume it is a new install. If you delete all the data in all tables and run the admin app again it'll go through the category creation again.

**Comment by kayleeg00se** [comment]
Thanks for the quick reply. Yes, just installed yesterday. I added this Engineering category myself directly in the table because it wouldn't allow me to add it through the manager app. I entered all the fields exactly the same as the ones that were there when I installed the app, just changed the name. The other categories work fine, but the ones I added to the table manually don't show the prompt field. Is there another entry I need to make besides in the "Employee Idea Campaign" table?

**Comment by xmpierce1** [comment]
To add to this. Is there a customized walkthrough to add categories like "Sales" in Prompt Buddy for those who are not techies? I like to add this to an adoption vehicle for clients and a no cost leave behind but they will ask for something like this without editing the app itself

**Comment by stuartridout** [comment]
@xmpierce1 there is another app, the Prompt Buddy Manager app that allows you to add categories.

**Comment by kayleeg00se** [comment]
> @xmpierce1 there is another app, the Prompt Buddy Manager app that allows you to add categories.

I was using the manager app to add categories, but attempted the workaround because the dropdown to select the category type was always disabled. The workaround I found that works now is just to add the items without selecting the category type, then choosing the type in the data table in the backend.
