### ISSUE TITLE
Not seeing "Copy to Clipboard" for prompts after installation

### ISSUE THREAD

**Issue by stevedistef** [stuartridout/promptbuddy#21]
I am the owner of a Teams site in an enterprise customer of Microsoft.
I followed the instructions and installed Prompt Buddy yesterday.
While I can see all the prompts which I imported as part of the zip file provided in this repo, I do not see the _copy to Clipboard_ button on the pages where the prompts are visible.
Example:
Starting here I see there are 6 prompts:
![image](https://github.com/stuartridout/promptbuddy/assets/159309739/9aeb7d00-10be-42d7-ad5d-6a5e4b1ae3d3)

I can click any one of them which advances me to its own page:
Notice on this page there is no "Copy to Clipboard" button...
![image](https://github.com/stuartridout/promptbuddy/assets/159309739/4f96bda1-b77e-4ae5-8fd7-e45df23c72e8)

Is there not supposed to be a copy button?
Or are we expected to manually copy the text and go paste it into our respective copilot?

**Comment by tphenkel** [comment]
I have been looking for this too. We need a way to easily copy a prompt, similar to the buttons in Copilot Labs

**Comment by stuartridout** [comment]
Hi there,

Unfortunately the Copy button is only visible if the Power App is viewed outside of Teams (which incurs extra licensing).  This is a restriction of Power Apps in Teams as the Power App doesn't have access to the clipboard.  

We're looking for alternative ways to do this at the moment that makes it easier than today.

**Comment by yosoyx** [comment]
I actually modified my local version and added the copy icon
<img width="849" alt="copy prompt" src="https://github.com/stuartridout/promptbuddy/assets/79267198/7c071e4e-cc56-4e7b-8657-a040e0262d5c">

On the Campaign details screen inserted the the built in Copy icon and set the  onselect = Copy(txtResponseText.Text);Notify("Prompt Copied to Clipboard",NotificationType.Success,3000).

To make it easier, open the Prompt Buddy in edit mode, run preview, select and existing prompt, which will take you to the details screen, exit preview mode an insert the icon where it makes more sense to your experience.
