### ISSUE TITLE
'Copy' prompt button idea

### ISSUE THREAD

**Issue by michalbednarskireckitt** [stuartridout/promptbuddy#22]
Just an idea from my end - it would be very convenient for users if they could just click 'Copy' next to the prompt (example below), so they don't have to manually mark and copy the instructions 😊
![image](https://github.com/stuartridout/promptbuddy/assets/170467783/aa66ed00-d760-400b-8136-9a9d9267864b)

**Comment by devinhenkel** [comment]
I actually tried adding a copy button, but couldn't get it to reference the current text. But, I second the request for a copy button. I think it would increase adoption.

**Comment by michalbednarskireckitt** [comment]
It definitely would, looking forward to the update then ;)

**Comment by stuartridout** [comment]
Unfortuately a Power App in Teams cannot access the clipboard so we cannot provide a Copy button for this scenario.  We are investigating other ways to make it easier to highlight and copy manually.
