### ISSUE TITLE
Admin governance

### ISSUE THREAD

**Issue by michalbednarskireckitt** [stuartridout/promptbuddy#23]
Is there any chance, there are plans to provide edit/remove access to admins, so they can moderate the content in the app? E.g. they could remove duplicated prompts?

**Comment by stuartridout** [comment]
Hi. 

The admin app has the option to delete a prompt.  We've added the ability for people to edit or delete their own prompts in the main app.  

We're currently looking at being able to extend that to admins in the main app too.

**Comment by michalbednarskireckitt** [comment]
Thanks Stuart, I just saw that as an admin I can now also remove the prompts created by other users - maybe an edit permission would be a nice addition as well?

**Comment by stuartridout** [comment]
We've got on the roadmap to utilise the edit and delete functions within the app itself for the admin users so they don't have to switch app.
