### ISSUE TITLE
Adding Prompt Buddy to Shared Channels 

### ISSUE THREAD

**Issue by shollon11346** [stuartridout/promptbuddy#25]
We are wanting to utilize Prompt Buddy within shared channels in Microsoft Teams. In our testing we can add the app to both public and private channel, but not shared channels. Is adding to shared channels a known issue?

**Comment by stuartridout** [comment]
Unfortunately I cannot find anything to say whether Dataverse for Teams in Shared Channels is a support scenario.  I do have guidance on sharing an app beyond the team which may be useful in your case.  https://learn.microsoft.com/en-us/power-apps/teams/set-perms-and-share
