### ISSUE TITLE
Approval step for new prompts

### ISSUE THREAD

**Issue by cedricneo** [stuartridout/promptbuddy#26]
I really like Prompt buddy, it's got a very nice UX and UI and it's customizable.
However for large companies it's not possible to let all employees add their own prompts or we might end up with too many prompts and it will be difficult to find the really good ones.
Have you planned to add a feature so Admins (in the Prompt Buddy Manager app) could approve or reject submitted prompts? I would be awesome! Or at least have a way to restrict some users to add new prompts. 

Thanks again for your great work.

**Comment by CraigThompson-Dev** [comment]
I second this, attempting to roll it out to an org of 10k+ users.

**Comment by stuartridout** [comment]
I've added this to the backlog but currently there are no plans to include this.   We are looking at ways to make it easier to discover prompts as well as being able to create curated recommended prompts from the organisation.

**Comment by cedricneo** [comment]
> If anyone comes looking for this, we added a visible condition on the galleries to only include those that have an "accepted" status. Added a hidden admin screen with a simple form to update those.

Great! Which version/release contains that feature?
