### ISSUE TITLE
Problems adding the app to Teams

### ISSUE THREAD

**Issue by rubiasamagaio** [stuartridout/promptbuddy#28]
When I try to add it to Teams as an application, it displays an error screen stating that the application could not be found

![image (3)](https://github.com/stuartridout/promptbuddy/assets/173472736/d5093c2a-d293-41b3-bb19-5e8d52e229c6)

**Comment by stuartridout** [comment]
You need to publish the app to the Team from the editor.  See https://learn.microsoft.com/en-us/power-apps/teams/publish-and-share-apps
