### ISSUE TITLE
Icons missing in prompts lists

### ISSUE THREAD

**Issue by ClaireAtAvanade** [stuartridout/promptbuddy#29]
When navigating into the prompts per apps
Icons does not show (cf attachment)
![image (1)](https://github.com/stuartridout/promptbuddy/assets/173942864/2be6a626-db52-4c6d-9113-9718846727af)
Is it missing from the pack(PromptBuddy_1_0_3_1) ? or is it due to my (poor) integration :'p
Thanks in advance for your support

**Comment by mncannava** [comment]
Same, can confirm this happens on our install of 1.0.3.1 -- new regression from prior version.

**Comment by stuartridout** [comment]
Let me look into this.  We have a new version coming shortly.

**Comment by hallgrimeco** [comment]
Experience the same when installing 1.0.3.1

**Comment by Erithano** [comment]
### **This has been fixed** within the 1.5.0.0 release ✅! 
Thanks for reporting this @hallgrimeco, @mncannava and @ClaireAtAvanade

**Comment by Erithano** [comment]
Happily closing this issue as it's been fixed in the latest release of Prompt Buddy!
#HappyUpdating
