### ISSUE TITLE
Adding Prompt Buddy to Shared Channel w/ Microsoft Support

### ISSUE THREAD

**Issue by shollon11346** [stuartridout/promptbuddy#30]
Hello, we took the provided guidance to add Prompt Buddy to Teams and it is now available to install in either a channel (private and standard only), a chat, or a meeting. We opened a support ticket with Microsoft since we were unable to add to a shared channel and Microsoft would like to know if the attribute for that schema has been added per the documentation provided below by Microsoft. If it has been added, they recommend working with Microsoft developers to troubleshoot further. 

 https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#supportedchanneltypes

**Comment by stuartridout** [comment]
Power Apps is not currently supported in shared channels, shared channels have some limitations on the tabs that can be added, and Power Apps is not listed as one of the available tabs. 

The attribute mentioned in the original post is for a custom build app manifest e.g. from a pro code app.
