### ISSUE TITLE
Not possible to edit "Tag multiple apps, departments and personas" field

### ISSUE THREAD

**Issue by stasfeelin** [stuartridout/promptbuddy#31]
After you posted a prompt you can edit anything but "Tag multiple apps, departments and personas"

<img width="3068" alt="image" src="https://github.com/stuartridout/promptbuddy/assets/33052570/c7e5ca5f-e7e3-4f63-a1c7-9e36f3d89382">

**Comment by stasfeelin** [comment]
some people accidentally select wrong tag on creation and need to create from scratch to fix

**Comment by stuartridout** [comment]
Hi,

It's on the backlog to be able to edit that.  It's coming soon.

Stuart

**Comment by anthonyvigneron** [comment]
yes we need this too!
