### ISSUE TITLE
image doesn’t save

### ISSUE THREAD

**Issue by IwonaUSPZ** [stuartridout/promptbuddy#36]
When we add a new prompt along with an image to the prompt, the image doesn’t save, and we keep seeing the default image instead. Do you know why this might be happening and could you suggest how to fix it?

**Comment by stuartridout** [comment]
That is an odd one.  We've not seen that before.  

Do you have any other information?  Image file size?  Image type?  Error messages?

**Comment by IwonaUSPZ** [comment]
Hi Stuart, thanks for reaching out. I’m just attaching a photo in HTML format. There’s no error message, and the photo doesn’t get saved, but maybe I should only be attaching images in jpg or png format (I just realized this now ;))?

**Comment by Erithano** [comment]
@IwonaUSPZ 

Yes, please use a non-html format such as jpg or png 💗👍

(Also have a look at the latest Prompt Buddy release that, among many things, fixes an image-related issue for prompt images when viewed as a list in a category.)
