### ISSUE TITLE
prompt that can create images in the PromptBuddy graphic style

### ISSUE THREAD

**Issue by IwonaUSPZ** [stuartridout/promptbuddy#38]
I’ve been watching your videos on YouTube n one of your videos, you mentioned a prompt that can create images in the PromptBuddy graphic style (origami). Would you be able to share that with me?

**Comment by stuartridout** [comment]
When you install Prompt Buddy, in the admin interface there is an option to import some prompts.  One of the ones in the Designer category is this prompt.  

You can either go to [https://designer.microsoft.com/image-creator?p=Origami+art+representing+%5Bfinance+as+a+business+department%5D%2C+in+gradient+colors+and+dark+background.+&referrer=PromptTemplate ](https://designer.microsoft.com/image-creator?p=Origami+art+representing+%5Bfinance+as+a+business+department%5D%2C+in+gradient+colors+and+dark+background.+&referrer=PromptTemplate )

or just go to Designer and use the prompt 

`Origami art representing [Finance as a business department], in gradient colors and dark background. `

**Comment by IwonaUSPZ** [comment]
Hi Stuart, thanks for reaching out. I’ll check that, thanks for the guidance. :)
