### ISSUE TITLE
Add a copy icon to the prompt

### ISSUE THREAD

**Issue by RolfCloud42** [stuartridout/promptbuddy#4]
Hi, all worked out as described in the video. Big thanks for that. One element that I want to suggest is to have a icon at the prompt to copy the prompt to the clipboard for pasting it into the respective app.. Yes, we all know how to copy and paste but wouldn't that be so much more convenient?
I tried to add that myself in the solution but the naming and layering of the app did not make it easy to find. Any pointers would be highly appreciated.
![CopyPrompt](https://github.com/stuartridout/promptbuddy/assets/14055953/8fcd165e-02e1-4c01-8262-4662fa6b088d)

**Comment by stuartridout** [comment]
Closed as technically not possible.  Power Apps in Teams can't access the clipboard unfortunately.

**Comment by RolfCloud42** [comment]
Hi Stuart and team. Sorry to bug you again but maybe this points into the right direction?
https://powerusers.microsoft.com/t5/Building-Power-Apps/How-do-I-create-a-copy-to-clipboard-button-in-PowerApps-for/td-p/891721

**Comment by Erithano** [comment]
You're not bugging us Rolf! @RolfCloud42 - Appreciate your efforts to improve Prompt Buddy for all.
As Stuart mentioned we have a working button **when** the Power App is used in a browser. We had to remove it as Power Apps does not technically support this feature when used in Microsoft Teams.

We will revisit and do some testing with your suggestion from the forum. We're pessimistically optimistic based on our previous efforts 🙂
