### ISSUE TITLE
How to allow the buddy to be accessible from Copilot within the M365 productivity suite

### ISSUE THREAD

**Issue by Roxy22-ai** [stuartridout/promptbuddy#40]
I have been testing the Prompt Buddy. Is there anywhere I can find more information about how the buddy will be accessible from Copilot within the M365 productivity suite? For example, when in Excel I want to quickly access the Prompt Buddy Excel library of prompts that my teams uses in Excel. Thank you

**Comment by Erithano** [comment]
Hey @Roxy22-ai!

We here this suggestion sometimes and we're actively looking at different options of bringing Prompt Buddy prompts closer to the user (in product access). One such initiative (Microsoft internal for now) is building a Copilot Agent (also known as Declarative agents) for this purpose. 

We won't have any short-term updates to share here, but we are actively exploring your scenario 💗
