### ISSUE TITLE
Copy prompt button

### ISSUE THREAD

**Issue by uf-aferrara** [stuartridout/promptbuddy#42]
It would be super helpful if there was a button that would allow you to copy the prompt to the clipboard.

**Comment by NicolasRenault** [comment]
Hello,

I tried to implement it.
Sadly, the function [Copy()](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-copy) doesn't work when the app is installed in Teams.  

If you're not using the Teams version, you can add a button next to the prompt and add to the "OnSelect" property the function [Copy()](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-copy) with the prompt text.

**Comment by Erithano** [comment]
As perfectly explained by @NicolasRenault, Power Apps cannot access the clipboard when used in Teams (a Microsoft Teams limitation).

Hence, we do not show a "Copy prompt to clipboard button" - We do have one if used in the browser...

Interesting fact: We discussed adding a "Copy Prompt"-button that would open the prompt text in a pop-up window. 
But users would still have to manually select and copy the text...

If you have any magica ideas to improve this, without access to the clipboard, please share with us 💌!

**Comment by Erithano** [comment]
As mentioned in my previous comment, this is a Teams limitation. Hence closing this issue, but feel free to reopen and engage around this!
