### ISSUE TITLE
Prompt counter (Top contributors) does not show the actual number of prompts

### ISSUE THREAD

**Issue by AlexSweetPotato** [stuartridout/promptbuddy#44]
Prompt counter (Top contributors) does not show the actual number of prompts. In the app shows 1 prompt but when you click over the contributor then you see that the actual number is 33 prompts.
![image](https://github.com/user-attachments/assets/7b55c086-c93c-4e8c-92f7-f8e4c31ddc63)
![image](https://github.com/user-attachments/assets/9192bca5-470a-4c82-acd2-6c203872bd4f)

**Comment by stuartridout** [comment]
Hi there.  Are they imported prompts? We don't show imported prompts in the leaderboard so as not to skew the statistics for the admin who normally would be the person to import the base prompts.

**Comment by AlexSweetPotato** [comment]
Ok, I understand! Yes, the contributor confirmed to me that the prompts were imported. 

Nevertheless, I was able (a couple of weeks ago) to saw the contributor's name in the Leaderboard with "1 prompt". Now has disappeared. It's that the expected behavour?

**Comment by AlexSweetPotato** [comment]
Ah! Now I got it! Yes, the contributor deleted one prompt (I guess the summited one) because I saw that was duplicated and I ask her to delete one of it.
