### ISSUE TITLE
Editing prompts edits prompts for everyone

### ISSUE THREAD

**Issue by volks7979** [stuartridout/promptbuddy#45]
As I validate this solution, it seems that anyone can edit any prompt which is then visible to everyone.
Is this working as designed?

**Comment by pacific202** [comment]
I'm ok with that, but versioning would be pretty important so prompts will never get lost or ruined.

**Comment by Erithano** [comment]
@volks7979 & @pacific202 
Users can edit/remove their own prompts. Not anyone else's. 

A Prompt Buddy Manager/Admin has access to edit/remove any prompt.

_Please update your Prompt Buddy to the latest version 😇_
