### ISSUE TITLE
Duplicate Categories

### ISSUE THREAD

**Issue by TimickXP** [stuartridout/promptbuddy#47]
We are seeing duplicate categories App, Department, and Persona in our Prompt Buddy. I updated to the latest Prompt Buddy hoping that would resolve with no luck. 

How would we go about removing the duplicates?

![Duplicate Categories](https://github.com/user-attachments/assets/fd4aa500-0ccd-4f4b-9792-87fe9e4ce653)

**Comment by Erithano** [comment]
We have not seen this before. Does this the issue still exist? @TimickXP 

We suggest doing a clean install to the most recent release. (New one just released!) 
(if you already have prompts in your version, you can export them to import in the new version).

Good luck 😊!
