### ISSUE TITLE
Prompts counter has disappear for one Top contributors

### ISSUE THREAD

**Issue by AlexSweetPotato** [stuartridout/promptbuddy#48]
The Prompts counter has disappear for one Top contributors
<img width="870" alt="Prompt Buddy issue 2" src="https://github.com/user-attachments/assets/4d0532bb-4c8c-4838-bbd8-c54fd9bfcaf5">

**Comment by stuartridout** [comment]
Hi there. Are they imported prompts? We don't show imported prompts in the leaderboard so as not to skew the statistics for the admin who normally would be the person to import the base prompts.
