### ISSUE TITLE
Power Apps license required to open on a web browser

### ISSUE THREAD

**Issue by cedricneo** [stuartridout/promptbuddy#49]
Hello, the app works perfectly fine as a tab in a team in Teams 💪. However when I click 'Go to website' or 'Open in browser' to open the Power Apps app in Edge, I get an error message "Your Power Apps trial has expired". I have a "Power Apps for Office 365" license but no other plans like Premium. Why do I get the error message? Why is it working fine when I view the app in Teams but not when I open it in a browser? Does the app contain Premium Connectors?
Many thanks in advance for your help.

**Comment by cedricneo** [comment]
<img width="532" alt="2024-09-04_13h00_35" src="https://github.com/user-attachments/assets/03384f93-1fff-4d30-8614-aecb8418d042">

**Comment by stuartridout** [comment]
The app uses Dataverse for Teams.  This is included in the standard licence for a Power App hosted in Teams but when viewed on the web it becomes a premium data source.
