### ISSUE TITLE
Compatible with New Teams?

### ISSUE THREAD

**Issue by alliehutch** [stuartridout/promptbuddy#5]
I was going through the installation.  I am using the new Teams client.  Got through adding both apps to my channel - but when I go to look at the channel - they aren't there.  I had the thought that maybe the new Teams is the problem.  I switched back to Classic Teams - the apps are listed as tabs within my channel.  I stayed in Classic teams to go through the rest of the setup.  Then I switched back to new Teams and the app was there.

**Comment by Erithano** [comment]
Thanks for sharing your experience @alliehutch 
Yes. 100 % compatible with New Teams.
There should be no issue with doing the full installation in New Teams. It might have been a Teams cache issue on your side.
By switching between Classic and New Teams you might have gotten the same results as if signing in and out of new Teams.

Thanks again for sharing - Will help others in case something similar happens 👍
