### ISSUE TITLE
promptbuddy-1.0.3.1-release.zip

### ISSUE THREAD

**Issue by djaeroseb** [stuartridout/promptbuddy#50]
Can you tell me why when I import the zip I get the following message ? "The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported."

**Comment by stuartridout** [comment]
Are you trying to import it as a solution or trying to add it as an app?  You need to import the solution.  See the instructions.
