### ISSUE TITLE
How to change the text "Tag apps, departments and personas" in the submit/edit prompt screens

### ISSUE THREAD

**Issue by andrea-cu** [stuartridout/promptbuddy#51]
Hi, this isn't so much an issue - more of a question:

When users submit or edit a prompt, above the field where they choose a tag there is a label "Tag apps, departments and personas"

I've updated ours so that our category types are apps and topic, but I can't find where to update this instruction label. 

Does someone know where it is? I've gone through all the screens, at least I think I have, but can't find it. Any help would be appreciated :)

Thanks!

![Label to add tags](https://github.com/user-attachments/assets/b6a05185-4cdb-4bff-8c03-7c5465b8ec0a)

**Comment by Erithano** [comment]
@andrea-cu This should help you locate the sentence.

IMPORTANT: As of Prompt Buddy v 1.5.0.0 (October 2024) please know that the UI translations will break if you change the sentence. This might not be an issue for you, but if changed your new sentence will always display in English.
![image](https://github.com/user-attachments/assets/67a46437-5b30-494c-ba09-ddd3d020991b)

**Comment by andrea-cu** [comment]
Thank you so much @Erithano - I did try looking through every screen but couldn't find it (ugh sorry). Your screenshots are very helpful! Thanks also for the heads up about translations. We'll think carefully before making that change, being mindful of the potential impact :)

**Comment by Erithano** [comment]
[heart]         Erik Olsson reacted to your message:
________________________________

**Comment by Erithano** [comment]
You are most welcome @andrea-cu. Thanks for letting us know 😊
![New Prompt Buddy logo 192x192](https://github.com/user-attachments/assets/eb26f32b-2669-4d8b-9769-b2cbeda34bd6)
