### ISSUE TITLE
approval workflow by app managers before publishing to all staff

### ISSUE THREAD

**Issue by anthonyvigneron** [stuartridout/promptbuddy#54]
Is there a way to have prompts submitted approved by the manager roles first? (we work in very precise field so need to help ppl refine prompts they use before sharing globally!)

**Comment by Erithano** [comment]
@anthonyvigneron -YES! In the latest release (currently 1.5.0.0 when writing this) Prompt Approval is available!

When turned on (in the Prompt Buddy Manager settings), all prompts submitted are sent to designated approvers for approval.

This is fully integrated with the Microsoft Approvals app. Once an approval request comes in, it can then be forwarded to the relevant manager by the designated approvers.
