### ISSUE TITLE
Add Post to Engage or Teams (Not just Teams)

### ISSUE THREAD

**Issue by TheGeneralLedge** [stuartridout/promptbuddy#58]
Hi

I really like the idea of Prompt buddy and plan to review it in more detail and share with some colleagues.

Instead of MS Teams we are using a Viva Engage Community for our users - it would be great is there could be an option to post to engage with a given 'Topic' when people add prompts.

I am looking to install the app standalone in PowerApps vs within teams so being able to post about new prompts in Engage via automation would be brilliant and align with our user community support model.

Thanks

Graham

**Comment by Erithano** [comment]
@TheGeneralLedge - That is possible to build.
Check the Prompt Pulse app on GitHub (by our colleagues). It has integration with Prompt Buddy - but it also allows you to share prompts from Prompt Buddy to Viva Engage: https://aka.ms/promptpulse
