### ISSUE TITLE
Number of Prompt?

### ISSUE THREAD

**Issue by dktoa** [stuartridout/promptbuddy#59]
Hi,

I have just updated my Prompt Buddy to the latest version.

Why do I see App, Department and Persona 3 times and why can't I see how many prompt I have in each category? Please see attachments

![PromptBuddy](https://github.com/user-attachments/assets/39606483-75f0-44bd-ad5e-0e507f447a25)
![PromptBuddy1](https://github.com/user-attachments/assets/2fce6223-aa32-49ff-935d-9d1d56021da2)

**Comment by Erithano** [comment]
@dktoa - First - Love that your using Prompt Buddy in Danish!

> why can't I see how many prompts I have in each category?
When Prompt Approval is turned ON you won't see the number of prompts in the main view. The number of prompts display correctly in each category. This is a known limitation.

> Why do I see App, Department and Persona 3 times?
This looks like a strange, isolated bug. To resolve it:
1. Open Power Apps in Teams
2. Navigate to where prompt Buddy is installed and click "See all"
3. Edit the table called Campaign Category and delete your copies:
![image](https://github.com/user-attachments/assets/0d34fcff-e447-4f57-b7bf-396d67d71139)

**Comment by dktoa** [comment]
@Erithano - thanks a lot for your answer - issue solved
