### ISSUE TITLE
How to restrict Category visibility

### ISSUE THREAD

**Issue by eclerici2111** [stuartridout/promptbuddy#6]
As per my understanding the feature update to change the app category visibility is scheduled for release in an upcoming version of the app. Could you please inform me which version will include this update? Additionally, is there a workaround to implement this change in the current version?
Many thanks
Enrico

**Comment by Erithano** [comment]
Hey Enrico! 
Not sure what you mean exactly @eclerici2111. 

You can deploy Prompt Buddy into different Teams and have different categories in each installation.
Only team members and team owners will have access and that's a way to restrict visibility of different prompt categories. Apologies if I didn't understand your question correctly.

We do not have feature update information to share for potential future versions at this time.

Hope that helps!

**Comment by Erithano** [comment]
No plans to share at the moment.
