### ISSUE TITLE
Importing promts

### ISSUE THREAD

**Issue by franzskaaning** [stuartridout/promptbuddy#64]
Maybe not an error. But as by design.
But! When I import promts, I add my own IDs to the json, but these IDs are not used, so I get duplicates.

**Comment by Erithano** [comment]
@franzskaaning - Well spotted. 

The IDs are **NOT** needed for import. Please remove that line from the your JSON. 
Once your prompts are imported, they get a unique ID.

Exported prompts will include the ID to avoid duplication - That's why you see them in the sample prompts for example.
