### ISSUE TITLE
Cannot submit prompt

### ISSUE THREAD

**Issue by cvb73** [stuartridout/promptbuddy#66]
I get an error by submitting a prompt in field: 

"You must add at least one app tag"

But I have add a tag

**Comment by ostromecko** [comment]
App tag is the name of application, like word excel etc. Are you submitting a prompt with this category added?

**Comment by cvb73** [comment]
After installing the app was empty. I create some categories. IfI try to submit a new prompt the category is pre-filled but the red flaged headline of this field says I have to select one.

**Comment by Erithano** [comment]
@ostromecko provided the solution. Thanks for this! 

By enforcing the "App" tag all prompts are tagged to the Copilot or AI app they're designed for.
This is good when adding direct from a non-App category such as a Department.

Closing this issue.
