### ISSUE TITLE
Share in channel?

### ISSUE THREAD

**Issue by rimetree** [stuartridout/promptbuddy#69]
When notifications are enabled in Prompt Buddy Manager, this toggle is visible. However, it doesn't seem to matter if it's on or off...a new prompt will always trigger a notification to the announcements channel. I just upgraded to 1.5 so just checking to see if this is expected behavior or not. Thanks.

**Comment by Erithano** [comment]
Hi @rimetree!

This is a known issue. You will find the workaround documented here: #57 ✅
