### ISSUE TITLE
Where to find the Localizations Excel?

### ISSUE THREAD

**Issue by th0rG3r** [stuartridout/promptbuddy#7]
Where is the place we can confige the Localization Excel?

**Comment by Erithano** [comment]
@th0rG3r 
Currently, a localization excel is not something we provide. Extracting from the Power App is not really an option. 
However, it's on our Backlog! 

We are working towards providing localization (in progress) and then aim to provide a localization excel for the community to add/update multiple languages. Hope that helps for now 🙂👍

**Comment by Erithano** [comment]
We're still working on this, and will update here if/when available 👍

**Comment by Erithano** [comment]
Still working on this 😊 - We know many of you are excited about this. 
Especially with Copilot now adding 16 new languages (30 April)

We're not machine translating but instead leveraging native speakers for multiple languages to deliver localization with the highest quality.

**Comment by Erithano** [comment]
Update:

Internally we have now completed Swedish and have multiple languages in review stages with regards to a localization excel @th0rG3r

**Comment by Erithano** [comment]
@th0rG3r & @Roxy22-ai  - Happy to provide the current localization file for you to experiment with.
It's included in the latest Prompt Buddy release but can't be easily exported from the solution.
So here it is!

[staticLocalizations (Prompt Buddy October 14th, 2024).xlsx](https://github.com/user-attachments/files/17363229/staticLocalizations.Prompt.Buddy.October.14th.2024.xlsx)
