### ISSUE TITLE
My likes tab doesn't open

### ISSUE THREAD

**Issue by ostromecko** [stuartridout/promptbuddy#70]
We have upgraded to 1.5 version, and when we have liked prompts, we cannot enter the My Likes tab. Either from home page or category tree view.

**Comment by Erithano** [comment]
@ostromecko 

Is something happening, flashing or anything? Are you a user or admin?

If shared with users outside the team where Prompt Buddy is installed - Make sure to share access to all tables as described in #46

**Comment by ostromecko** [comment]
I'm the admin. But I will close this ticket, there was some misunderstanding of how the tab works.

**Comment by Erithano** [comment]
[like]  Erik Olsson reacted to your message:
________________________________
