### ISSUE TITLE
Uninstalling Prompt Buddy and reinstalling it

### ISSUE THREAD

**Issue by Eco-Admin-Oberaula** [stuartridout/promptbuddy#76]
We tried to install PB in a channel, this did not seem to work. So we used a new channel that was labeled “General”. Here it could be installed, but for some reason the manager was not installed. So we uninstalled PB and started again. Unfortunately, there still seems to be some remnants of the Canvas app in the system that we can't get rid of. Because every time we start the installation routine again, it has been saying for days: “Preparation in progress”.
Otherwise nothing happens. Does anyone have a tip for us on how we can solve the problem?

**Comment by Erithano** [comment]
@Eco-Admin-Oberaula - Sorry to hear about this random issue.

Are you able to create a new team and install Prompt Buddy there?

Each team gets a separate Power Apps environment when the first new app is created in it via the Power Apps app in Teams.

Please try with a new team (new environment) and let us know how it goes here.

Don't worry if not all your users are there. Prompt Buddy can easily be shared with users outside the team in which it's installed. See my guide in #46

**Comment by Eco-Admin-Oberaula** [comment]
Hi,

thank you for your reply. Somehow, after a week or so, the rest of the installation was gone and we were able to start all over agein. Now everything works fine. It's a great tool to help us with our prompts. Thank you for that!

________________________________
Von: Erik Olsson ***@***.***>
Gesendet: Donnerstag, 5. Dezember 2024 16:45
An: stuartridout/promptbuddy ***@***.***>
Cc: Rico Lipphardt ***@***.***>; Mention ***@***.***>
Betreff: Re: [stuartridout/promptbuddy] Uninstalling Prompt Buddy and reinstalling it (Issue #76)


@Eco-Admin-Oberaula<https://github.com/Eco-Admin-Oberaula> - Sorry to hear about this random issue.

Are you able to create a new team and install Prompt Buddy there?

Each team gets a separate Power Apps environment when the first new app is created in it via the Power Apps app in Teams.

Please try with a new team (new environment) and let us know how it goes here.

Don't worry if not all your users are there. Prompt Buddy can easily be shared with users outside the team in which it's installed. See my guide in #46<https://github.com/stuartridout/promptbuddy/issues/46>

**Comment by Erithano** [comment]
Thanks for verifying @Eco-Admin-Oberaula

Love the feedback! 

We hope to share some new updates soon...
