### ISSUE TITLE
Add another category to prompt

### ISSUE THREAD

**Issue by ostromecko** [stuartridout/promptbuddy#79]
@Erithano regarding issue #74, In which way admin can edit categories? I have tried through app, and also from data verse table. It's not doable from my end. In the data verse table, each row accepts only one category.

**Comment by Erithano** [comment]
As and admin, go to any prompt and choose "Edit". You can then tag that prompt into the categories you want ✌️

1. 
![image](https://github.com/user-attachments/assets/102eb832-0aee-4e3a-8ae2-3ce14b7d511f)

2.
![image](https://github.com/user-attachments/assets/edbce0cb-9cf3-4e0c-89c1-59af64e8d8d7)

**Comment by Erithano** [comment]
Feel free to reopen the issue if you're not able to do this. We hope this solves it for you.

**Comment by ostromecko** [comment]
Admin of the team? I mean, owner? We have this issue that I'm the owner but some settings for me are greyed out, and I cannot edit promts. 
![image](https://github.com/user-attachments/assets/7bae56af-537a-4487-b1a1-83ca7872d7a2)
![image](https://github.com/user-attachments/assets/8f4fcbc4-4a98-4078-8518-152e6c09a194)

**Comment by Erithano** [comment]
Thanks for sharing @ostromecko!

I meant Admin for Prompt Buddy. The person installing it becomes an Admin by default for example. 
Can you see if that person, unless that's you 🙃, has the edit option on the prompts?
