### ISSUE TITLE
Manager - Can't View Categories After Cancelling The Creation Of A New One

### ISSUE THREAD

**Issue by AarnavDAA** [stuartridout/promptbuddy#8]
In the manager, if I press "Add Category" and then press "cancel" to exit out of the category creation form, then every time I click on a category (app, persona, department, anything) I am greeted with the category creation from instead of a list of prompts that fall under the category I clicked. This does not go away until I actually create a new category, however if I cancel the creation of another new category, the issue starts all over again.

**Comment by AarnavDAA** [comment]
Fixed it after a few hours.

Pretty janky but I copied 
`    UpdateContext(
        {
            locVisibleCampaignEdit: false,
            locVisibleCampaignView: locVisibleCampaignEdit,
            locVisibleCampaignCreate: false,
            locCreateNewCampaign: false,
            locShowCampaignFormErrors: false,
            locVisibleCampaignIdeaSubmitted: locVisibleCampaignCreate,
            locIsSubmittedCampaign: true
        }
    );`
From the "Add Category" button's `OnSelect` property and pasted it into cancel button's `OnSelect` property in the second parameter of the If function at the beginning:

`If(
    locCreateNewCampaign,
    // Return to Main Screen, came from there
    Navigate(
        'Campaign Summary Screen',
        ScreenTransition.Fade
    );
    UpdateContext(
        {
            locVisibleCampaignEdit: false,
            locVisibleCampaignView: locVisibleCampaignEdit,
            locVisibleCampaignCreate: false,
            locCreateNewCampaign: false,
            locShowCampaignFormErrors: false,
            locVisibleCampaignIdeaSubmitted: locVisibleCampaignCreate,
            locIsSubmittedCampaign: true
        }
   ...`

**Comment by Erithano** [comment]
Thanks @AarnavDAA ! This bug was already on our backlog, but not yet started. Grateful for your contribution 🙏
Pending tests, we will incorporate the fix into a future release! 

Current workaround: Reload the tab / Manager App

**Comment by AarnavDAA** [comment]
Seems good, thanks for the update. 👍

**Comment by AarnavDAA** [comment]
Seems good, thanks for the update. 👍
