### ISSUE TITLE
As dataverse for Teams will be deprecated, can it be supported on a different Databse?

### ISSUE THREAD

**Issue by guilhermelimait** [stuartridout/promptbuddy#9]
As dataverse for Teams will be deprecated, can it be supported on a different Databse?

**Comment by RolfCloud42** [comment]
Maybe it does not even need a database but a list in SharePoint would server many customers. Just my 2ct

**Comment by guilhermelimait** [comment]
I totally agree, I was even thinking to recreate the app basing it on a simple sharepoint list internally

**Comment by Erithano** [comment]
It works perfectly well in Dataverse as well 😉

**Comment by Erithano** [comment]
> As dataverse for Teams will be deprecated, can it be supported on a different Databse?

@guilhermelimait - Dataverse for Teams is a supported and active part of the Microsoft ecosystem.
What source did you base your comment on?

**Comment by halukpn** [comment]
Since when is dataverse for teams being deprecated?

**Comment by Erithano** [comment]
> Since when is dataverse for teams being deprecated?

It's not. 
Both Stuart and I work at Microsoft HQ. There is no such announcement.
